name: CI

on:
  push:
    branches:
      - '*'
    paths:
      - '**.go'
  pull_request:
    paths:
      - '**.go'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Setup Go
      uses: actions/setup-go@v2
      with:
        go-version: '1.17'

    - name: Check for Go files
      run: |
        if [ -z "$(git diff --name-only ${{ github.event.before }} ${{ github.sha }} -- '**.go')" ]; then
          echo "No Go files modified, skipping workflow."
          exit 0
        fi

    - name: Download dependencies
      run: go mod download

    - name: Run tests
      run: go test -v ./...

    - name: Install linters
      run: |
        go install github.com/golangci/golangci-lint/cmd/golangci-lint@latest
        go install github.com/mgechev/revive@latest
        go install golang.org/x/lint/golint@latest
        go install honnef.co/go/tools/cmd/staticcheck@latest

    - name: Run linters
      run: |
        golangci-lint run ./...
        revive -config revive.toml -formatter friendly ./...
        golint ./...
        staticcheck ./...

    - name: Code coverage
      run: go test -coverprofile=coverage.out ./... && go tool cover -func=coverage.out
